test: i am a string
environment: staging
replicaCount: 3

# setting for nginx
image:
  name: "nginx" 
  tag: "1.27-alpine"

  #setting for service
service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80
